### ISSUE TITLE
Add 'Made with love in India' Badges for READMEs

### ISSUE THREAD

**Issue by plibither8** [AnandChowdhary/made-with-love-in-india#1]
Hey, for the couple of projects of mine, which I've hosted on GitHub, I've used a 'Made with love in India' badge at the top of the README. Something like this:
 
[![Made_with_love_in India](https://img.shields.io/badge/Made_with_love_in-India-DC3545.svg?style=flat-square)](https://madewithlove.org.in/)

This badge is of course being *hosted* on shields.io. It would be great if the website for MWLII could allow users to add such a badge by simply giving them the markdown code and link to the image. (I had to use a badge generator to make it). Moreover, it would look tons better and more professional if the badge image itself is hosted on the MWLII website.

The badge might not be used a lot, and updating the website for this change might be a bit of a pain, (I'd understand it more than anyone, trust me) but I guess it's worth it. If websites and its derivative products can include a small hyperlink to your website, I think open source software should too have something akin, and that is badges. I'm willing to contribute if needed! :smile: 

Thanks!

**Comment by AnandChowdhary** [comment]
Really good idea! I'm uploading an implementation on our CDN, feel free to contribute here: https://github.com/AnandChowdhary/made-with-love-in-india/blob/master/badge.svg

**Comment by plibither8** [comment]
Looks great! How’s it to be linked though? By linking directly to https://raw.githubusercontent.com/AnandChowdhary/made-with-love-in-india/master/badge.svg or is it going to be uploaded to the website too?
